backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "champions"
    label: "Champions"
    folder: "champions"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "ppvs"
    label: "PPVs"
    folder: "ppvs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Matches", name: "matches", widget: "list", fields: [
          { label: "Match", name: "match", widget: "string" },
          { label: "Result", name: "result", widget: "string" }
        ] }

  - name: "roster"
    label: "Roster"
    folder: "roster"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Bio", name: "bio", widget: "markdown" }
